name: BukkitFullOfMoon
main: com.dinnerbone.bukkit.moon.BukkitMoon
version: 1.13.5
api-version: 1.13
website: http://www.dinnerbone.com
author: Dinnerbone - Updated to 1.13.2/1.14.2 by JSW-TheOtherOne
description: From a Sample custom world generator for Bukkit
load: startup
commands:
  moon:
    description: Sends you to the moon!
    usage: /moon
  earth:
    description: Go back to earth!
    usage: /earth
  BMreload:
    description: Reloads the config file
    usage: /BMreload